=== MAIF/yozefu/docs/json-schemas/global-config.json
{
  "$id": "https://raw.githubusercontent.com/MAIF/yozefu/refs/heads/main/docs/json-schemas/global-config.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "GlobalConfig",
  "description": "Configuration of the application",
  "type": "object",
  "properties": {
    "default_url_template": {
      "description": "A placeholder url that will be used when you want to open a kafka record in the browser",
      "type": "string",
      "default": "http://localhost/cluster/{topic}/{partition}/{offset}"
    },
    "initial_query": {
      "description": "The initial search query when you start the UI",
      "type": "string"
    },
    "theme": {
      "description": "The theme to use in the TUI",
      "type": "string",
      "default": "light"
    },
    "highlighter_theme": {
      "description": "The theme to use for syntax highlighting",
      "type": [
        "string",
        "null"
      ]
    },
    "clusters": {
      "description": "The kafka properties for each cluster",
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/ClusterConfig"
      }
    },
    "consumer": {
      "description": "The default configuration for the yozefu kafka consumer",
      "$ref": "#/$defs/ConsumerConfig",
      "default": {
        "buffer_capacity": 1000,
        "timeout_in_ms": 10
      }
    },
    "default_kafka_config": {
      "description": "The default kafka properties inherited for every cluster",
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "history": {
      "description": "History of past search queries",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "show_shortcuts": {
      "description": "Show shortcuts",
      "type": "boolean",
      "default": true
    },
    "export_directory": {
      "type": "string",
      "default": "./yozefu-exports"
    },
    "log_file": {
      "description": "The file to write logs to",
      "type": [
        "string",
        "null"
      ]
    },
    "timestamp_format": {
      "description": "Show the timestamp as a date time or as \"X minutes ago\"",
      "$ref": "#/$defs/TimestampFormat",
      "default": "DateTime"
    },
    "display_order": {
      "$ref": "#/$defs/DisplayOrder",
      "default": "ascending"
    }
  },
  "required": [
    "initial_query",
    "clusters",
    "default_kafka_config",
    "history"
  ],
  "$defs": {
    "ClusterConfig": {
      "description": "Specific configuration for a cluster",
      "type": "object",
      "properties": {
        "url_template": {
          "description": "A placeholder url that will be used when you want to open a kafka record in the browser",
          "type": [
            "string",
            "null"
          ]
        },
        "schema_registry": {
          "description": "Schema registry configuration",
          "anyOf": [
            {
              "$ref": "#/$defs/SchemaRegistryConfig"
            },
            {
              "type": "null"
            }
          ]
        },
        "kafka": {
          "description": "Kafka consumer properties for this cluster, see <https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md> for more details",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "consumer": {
          "anyOf": [
            {
              "$ref": "#/$defs/ConsumerConfig"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "kafka"
      ]
    },
    "SchemaRegistryConfig": {
      "description": "Schema registry configuration of a given cluster",
      "type": "object",
      "properties": {
        "url": {
          "description": "Url of the schema registry",
          "type": "string",
          "format": "uri"
        },
        "headers": {
          "description": "HTTP headers to be used when communicating with the schema registry",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "default": {}
        }
      },
      "required": [
        "url"
      ]
    },
    "ConsumerConfig": {
      "description": "Configuration for the kafka consumer",
      "type": "object",
      "properties": {
        "buffer_capacity": {
          "type": "integer",
          "format": "uint",
          "minimum": 0
        },
        "timeout_in_ms": {
          "type": "integer",
          "format": "uint64",
          "minimum": 0
        }
      },
      "required": [
        "buffer_capacity",
        "timeout_in_ms"
      ]
    },
    "TimestampFormat": {
      "type": "string",
      "enum": [
        "DateTime",
        "Ago"
      ]
    },
    "DisplayOrder": {
      "description": "The order in which records are displayed in the TUI",
      "type": "string",
      "enum": [
        "ascending",
        "descending"
      ]
    }
  }
}

=== MAIF/yozefu/crates/app/tests/inputs/12709164435820766538.json
{
  "default_url_template": "",
  "initial_query": "from end - 10",
  "theme": "default",
  "highlighter_theme": null,
  "clusters": {},
  "consumer": {
    "buffer_capacity": 1000,
    "timeout_in_ms": 10
  },
  "default_kafka_config": {},
  "history": [],
  "show_shortcuts": false,
  "export_directory": "./yozefu-exports"
}
